server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
       routes:
        - id: DISCOVERY-SERVICE
          uri: lb://DISCOVERY-SERVICE
          predicates:
            - Path=/discovery-service/**

