server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: DISCOVERY-SERVICE
          uri: http://localhost:8070
          predicates:
            - Path=/discovery-service/**


logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    study: DEBUG
